"""empty message

Revision ID: 353745a73c1d
Revises: 4862d8b9c272
Create Date: 2025-08-12 21:15:32.925365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353745a73c1d'
down_revision = '4862d8b9c272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_follow_once', ['follower_id', 'followed_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint('uq_follow_once', type_='unique')

    # ### end Alembic commands ###
